# $HOME/.config/alacritty/alacritty.toml
# by Ni 2024-02-26
[shell]
program = '/bin/zsh'

[window]
opacity = 0.7
padding.x = 10
padding.y = 10
decorations = "full"

[font]
normal.family = "FiraCode Nerd Font Mono"